name: Push - Validate, Build and Release

permissions:
  actions: write
  checks: write
  contents: write

on:
  push:
    branches:
      - develop

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  pre-checks:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.dependabot.outputs.result }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: dependabot check
        id: dependabot
        uses: Alfresco/alfresco-build-tools/.github/actions/github-pr-check-metadata@f37c44cc085236178ebb8834eb634b0b4b550a40 # v8.23.0
        with:
          gh-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          actor: 'dependabot[bot]'
          label: github_actions
      - name: pre-commit
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@f37c44cc085236178ebb8834eb634b0b4b550a40 # v8.23.0
        with:
          skip_checkout: true
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@fc87bb5b5a97953d987372e74478de634726b3e5 # v3.0.25

  build:
    runs-on: ubuntu-latest
    needs: pre-checks
    if: ${{ needs.pre-checks.outputs.skip != 'true' }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # 4.7.1
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: Alfresco/alfresco-build-tools/.github/actions/update-pom-to-next-pre-release@f37c44cc085236178ebb8834eb634b0b4b550a40 # v8.23.0
        id: update-pom-to-next-version

      - name: Update VERSION file
        run: |
          echo ${{steps.update-pom-to-next-version.outputs.next-prerelease}} > VERSION

      - name: Set VERSION env variable
        run: |
          VERSION=$(cat VERSION)
          echo set VERSION=$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set SONAR_SCANNER_OPTS
        shell: bash
        run: |
          echo "JACOCO_REPORT_PATH=${{ github.workspace }}/activiti-coverage/target/site/jacoco-aggregate/jacoco.xml" >> $GITHUB_ENV
          echo "SONAR_SCANNER_OPTS=sonar:sonar -Dsonar.host.url='https://sonarcloud.io' -Dsonar.organization='activiti' -Dsonar.projectKey='Activiti_Activiti' -Dsonar.coverage.jacoco.xmlReportPaths=${{ env.JACOCO_REPORT_PATH }}" >> $GITHUB_ENV

      - name: Build and Test with Maven (and maybe Deploy)
        shell: bash
        run: mvn deploy ${{ env.MAVEN_CLI_OPTS}} ${{ env.SONAR_SCANNER_OPTS }}
        env:
          MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Echo Longest Test Run
        uses: ./.github/actions/echo-longest-run

      - name: Configure git user
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_USERNAME@users.noreply.github.com
        env:
          GITHUB_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}

      - name: Create release tag
        run: |
          git commit -am "Release $VERSION" --allow-empty
          git tag -fa $VERSION -m "Release version $VERSION"
          git push -f -q origin $VERSION

      - name: Get branch name
        uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@f37c44cc085236178ebb8834eb634b0b4b550a40 # v8.23.0

      - name: Propagate
        uses: Alfresco/alfresco-build-tools/.github/actions/jx-updatebot-pr@f37c44cc085236178ebb8834eb634b0b4b550a40 # v8.23.0
        if: ${{ env.BRANCH_NAME == 'develop' }}
        env:
          DEVELOPMENT_BRANCH: ${{ github.ref_name }}
        with:
          version: ${{ env.VERSION }}
          auto-merge: 'true'
          labels: ${{ env.DEVELOPMENT_BRANCH }}
          base-branch-name: ${{ env.DEVELOPMENT_BRANCH }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          git-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-author-name: ${{ secrets.BOT_GITHUB_USERNAME }}

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always() && failure()
    steps:
      - name: Teams Notification
        uses: Alfresco/alfresco-build-tools/.github/actions/send-teams-notification@f37c44cc085236178ebb8834eb634b0b4b550a40 # v8.23.0
        with:
          webhook-url: ${{ secrets.TEAMS_NOTIFICATION_WORKFLOW_WEBHOOK }}
